### ISSUE TITLE
decoding error in joblib library

### ISSUE THREAD

**Issue by krzysiek98q** [tweag/FawltyDeps#374]
**Describe the bug**
When running FawltyDeps on the joblib library (1.3.2), I get an error.
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kris/ten_project/.tmp/joblib/joblib/venv/lib/python3.10/site-packages/fawltydeps/__main__.py", line 8, in <module>
    sys.exit(main())
  File "/home/kris/ten_project/.tmp/joblib/joblib/venv/lib/python3.10/site-packages/fawltydeps/main.py", line 362, in main
    analysis = Analysis.create(settings, stdin)
  File "/home/kris/ten_project/.tmp/joblib/joblib/venv/lib/python3.10/site-packages/fawltydeps/main.py", line 188, in create
    ret.undeclared_deps  # pylint: disable=pointless-statement
  File "/home/kris/ten_project/.tmp/joblib/joblib/venv/lib/python3.10/site-packages/fawltydeps/utils.py", line 225, in wrapper
    calculated: T = method(self)
  File "/home/kris/ten_project/.tmp/joblib/joblib/venv/lib/python3.10/site-packages/fawltydeps/main.py", line 156, in undeclared_deps
    return calculate_undeclared(self.imports, self.resolved_deps, self.settings)
  File "/home/kris/ten_project/.tmp/joblib/joblib/venv/lib/python3.10/site-packages/fawltydeps/utils.py", line 225, in wrapper
    calculated: T = method(self)
  File "/home/kris/ten_project/.tmp/joblib/joblib/venv/lib/python3.10/site-packages/fawltydeps/main.py", line 119, in imports
    return list(
  File "/home/kris/ten_project/.tmp/joblib/joblib/venv/lib/python3.10/site-packages/fawltydeps/extract_imports.py", line 201, in parse_sources
    yield from parse_source(source, stdin)
  File "/home/kris/ten_project/.tmp/joblib/joblib/venv/lib/python3.10/site-packages/fawltydeps/extract_imports.py", line 153, in parse_python_file
    path.read_text(), source=Location(path), local_context=local_context
  File "/usr/lib/python3.10/pathlib.py", line 1135, in read_text
    return f.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 64: invalid start byte
```

**To Reproduce**
I cloned the joblib library repository from github and ran the `fawltydeps` command. This caused the error that appeared above.

**Expected behavior**
Adding the `--verbose` option to the `fawltydeps` command shows that the problem occurs with the `./joblib/test/test_func_inspect_special_encoding.py` file.

Reading the file with the `cat` command shows that the `utf-8` decoder cannot be used to read the file.

```python
# -*- coding: big5 -*-


# Some Traditional Chinese characters: �@�Ǥ���r��
def big5_f():
    """�Ω���ժ����
    """
    # ����
    return 0
```

**Environment**
 - OS name + version: WSL 1.2.5.0 (Ubuntu 22.04.2 LTS)
 - Version of the code: Python 3.10.11 + fawltydeps 0.13.1'

**Comment by jherland** [comment]
Thanks for reporting. We need to recognize these encoding specifiers (`# -*- coding: big5 -*-`) and act accordingly.

Will address this when we find the time.

**Comment by jherland** [comment]
Thanks again for reporting this. I believe I have a fix for this in the linked PR.
